repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "mypy"
        language: python
        language_version: python3.12
        additional_dependencies: ["mypy==1.15.0"]
        types: [python]
        require_serial: true
        verbose: true
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: xenon
        name: xenon complexity check
        entry: xenon
        language: python
        additional_dependencies: ["xenon"]
        args:
          [
            "--max-absolute",
            "A",
            "--max-modules",
            "A",
            "--max-average",
            "A",
            "src",
          ]
        files: \.py$
      - id: radon-mi
        name: radon maintainability index
        entry: bash
        language: system
        args:
          [
            "-c",
            'output=$(radon mi --min B --show src); if [ -n "$output" ]; then echo "$output"; exit 1; fi',
          ]
        files: \.py$
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
default_stages: [pre-commit, pre-push]
default_language_version:
  python: python3.12
fail_fast: false
