flowchart LR
    subgraph Create Event
        StartCreate[Get Event data] -- Event Data --> Create[Create and Save Event based on data]
        Create -- Event Details --> DisplayDetails[Display Event Details]
    end

    subgraph List Events
        StartList["Get Events of Guild"] -- Raw Events --> Compile[Format to Discord-Compatible objects]
        Compile -- Formatted Events --> DisplayEvents[Display events sorted soonest first]
    end

    subgraph Show Event Details
        StartShow[Get Selected event] --> Embed[Show the Selected event in an embed]
    end
    
    subgraph Edit Event
        StartEdit[Get Selected event] --> Embed2[Embed the editing/Cancel button in the message]

        Embed2 -- IF Edit --> HandleEdit[Handle Edits]
        Embed2 -- IF Cancel --> HandleCancel[Handle Cancellation]
    end

    subgraph Delete Event
        StartDelete[Ensure the guild has events] --> HandleDelete[Handle deletion of the Event]
    end

    subgraph Announce Event
        StartAnnounce[Confirm announcement]
        StartAnnounce -- IF Cancelled --> HandleCancel0[Handle cancellation]
        StartAnnounce -- IF Announced --> HandleAnnounce[Make Announcement]
    end

    subgraph My Events
        StartMy[(Get User data)] --> Format[Format Events & Sort by soonest first]
        Format --> DisplayMyEvents[Display Events]
    end

